### ISSUE TITLE
Problem in EP <- get_hurdat(basin = "EP") and AL<- get_hurdat(basin = "AL")

### ISSUE THREAD

**Issue by Masih2768** [timtrice/HURDAT#3]
Hello, Could you please help me with my problem!
Thanks
![capture](https://user-images.githubusercontent.com/40285330/41449906-75b39ee0-703e-11e8-8cfd-70b197ba4833.PNG)

**Comment by timtrice** [comment]
This is a duplicate of #1. 

I will import the "%>%" in future releases but for now you can avoid this error by including the `dplyr` package.
